DROP TABLE IF EXISTS "saved";
DROP TABLE IF EXISTS "images";
DROP TABLE IF EXISTS "posts";
DROP TABLE IF EXISTS "categories";
DROP TABLE IF EXISTS "locations";
DROP TABLE IF EXISTS "users";
DROP TYPE IF EXISTS "sex";
